### STAGE 1:BUILD ###
FROM node:18 AS build
WORKDIR /app
COPY . .
RUN npm ci
RUN npm run build


### STAGE 2:RUN ###
FROM nginx:latest
RUN rm -f /usr/share/nginx/html/index.html
COPY --from=build /app/dist/* /usr/share/nginx/html
COPY nginx.conf  /etc/nginx/nginx.conf
EXPOSE 80
